line-length = 180
[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-bugbear
    "B",
    # isort
    "I",
    # NumPy-specific rules 
    "NPY",
    # pandas-vet 
    "PD",
]
ignore = [
    # Named lambdas
    "E731"
]
[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true